// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using NatCat.Platform.Data.Context;
using System;

namespace NatCat.Platform.Data.Migrations
{
    [DbContext(typeof(NatCatPlatformContext))]
    [Migration("20180420170012_sqlLite")]
    partial class sqlLite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("NatCat.Platform.Data.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("AverageRating");

                    b.Property<string>("Genre");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("NatCat.Platform.Data.Entities.StoryPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<int?>("StoryId");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryPart");
                });

            modelBuilder.Entity("NatCat.Platform.Data.Entities.StoryPart", b =>
                {
                    b.HasOne("NatCat.Platform.Data.Entities.Story", "Story")
                        .WithMany("StoryParts")
                        .HasForeignKey("StoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
